### ISSUE TITLE
Firtool complains on field access

### ISSUE THREAD

**Issue by bathtub-01** [rameloni/tywaves-chisel#42]
Hi.

I was trying Tywaves in my project. It works perfectly on most Modules, but for memory implementations like this:

```scala
class MemIOBundle[T <: Data](depth: Int, t: T) extends Bundle {
  val rdAddr = Input(UInt(log2Ceil(depth).W))
  val rdData = Output(t)
  val wrEna = Input(Bool())
  val wrData = Input(t)
  val wrAddr = Input(UInt(log2Ceil(depth).W))
}

class BlockMem[T <: Data](depth: Int, t: T) extends Module {
  val io = IO(new MemIOBundle(depth, t))

  val mem = SyncReadMem(depth, t)
  io.rdData := mem.read(io.rdAddr)

  when(io.wrEna) {
    mem.write(io.wrAddr, io.wrData)
  }
}
```

Firtool will raise complains, saying field access in annotation is not supported. The error message looks like this:
> [info] error: field access in annotation not supported for this operation
> [info]   io.rdData := mem.read(rdAddr)
> [info] error: field access in annotation not supported for this operation
> [info]   io.rdData := mem.read(rdAddr)

Are there any ways to get around this, without explicitly expand the io definition like this?

```scala
class BlockMem[T <: Data](depth: Int, t: T) extends Module {
  val rdAddr = IO(Input(UInt(log2Ceil(depth).W)))
  val rdData = IO(Output(t))
  val wrEna = IO(Input(Bool()))
  val wrData = IO(Input(t))
  val wrAddr = IO(Input(UInt(log2Ceil(depth).W)))

  val mem = SyncReadMem(depth, t)
  rdData := mem.read(rdAddr)

  when(wrEna) {
    mem.write(wrAddr, wrData)
  }
}
```

I am using the latest Tywaves version from this repo. Thank you :)

**Comment by rameloni** [comment]
This is weird, I do not expect this error (at least not anymore https://github.com/rameloni/chisel/commit/064e2f12020f4f3291842f4328d064d537c0415c). I quickly tested it with `0.4.1-SNAPSHOT` release and it seems to work fine.

I attached here a scala cli test example. Please, could you try it and let me know if it works or not?
[testSyncReadMem.zip](https://github.com/user-attachments/files/17401952/testSyncReadMem.zip)

Can you please send me your testbench example so I can reproduce the error? Or is your project open source so I can test it directly?

**Comment by bathtub-01** [comment]
You script works fine in my machine. I confirmed that using UInt as memory element won't trigger any error. However, with Bundle consisting ChiselEnum fields as memory element will cause the error report. 

Please check this script. Thank you.
[MemWithBundle.zip](https://github.com/user-attachments/files/17409673/MemWithBundle.zip)

**Comment by rameloni** [comment]
@bathtub-01 thanks! I'll check this out soon.

**Comment by rameloni** [comment]
@bathtub-01, I fixed the bug you can try this PR: https://github.com/rameloni/tywaves-chisel/pull/43

![image](https://github.com/user-attachments/assets/877a117b-9936-49f2-98eb-6e9376d0f564)

**Comment by rameloni** [comment]
You can find a new release here: [v0.4.2-SNAPSHOT](https://github.com/rameloni/tywaves-chisel/releases/tag/v0.4.2-SNAPSHOT).

**Comment by bathtub-01** [comment]
Thank you for this!

**Comment by bathtub-01** [comment]
@rameloni, I found similar error report occurs when using the `SRAM` interface with `ChiselEnum` as element field. I'm using the `0.4.2-SNAPSHOT` version.

You can reproduce the error with this script: 
[SRAMWithEnum.zip](https://github.com/user-attachments/files/17473524/SRAMWithEnum.zip)

**Comment by rameloni** [comment]
Hi @bathtub-01, I tested your example. The error generated is not related to the `ChiselEnum`, indeed the error message is also different. Thus, I'm closing this issue and moving the conversation to another.
